### ISSUE TITLE
MAT is not automatically installed

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.jl#114]
Although it is listed in test/REQUIRE.

**Comment by spencerlyon2** [comment]
The Julia testing system will install and un-install all packages in `test/REQUIRE` when you do `Pkg.test("QuantEcon")`. 

This means that the package won't remain in your Julia install unless you add it on your own.

**Comment by oyamad** [comment]
I see, thanks. (I did `julia runtest.jl mc_tools`; in this case I need to manually install it, right?)

**Comment by spencerlyon2** [comment]
Yeah, that’s exactly right. It isn’t the most convenient, but it is nice to
be able to specify dependencies that only developers need for testing
purposes.



// Spencer

On July 6, 2016 at 3:14:56 PM, Daisuke Oyama (notifications@github.com)
wrote:

I see, thanks. (I did julia runtest.jl mc_tools; in this case I need to
manually install it, right?)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/QuantEcon/QuantEcon.jl/issues/114#issuecomment-230784516>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA9J3PIzCRn12A5rNwXMlNdFL8BAcC88ks5qS7hfgaJpZM4JGHbI>
.
